server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static files correctly
    location /static/ {
        try_files $uri =404;
    }

    # React app routing
    location / {
        try_files $uri /index.html;
    }
}