version: "3"

services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend